sudo: required

services:
  - docker

env:
  matrix:
    - PROJECT=vault
  global:
    secure: NS9pjpEi7zuaINfFCUqQuagRJHd7gRLD4cH7+8yBsxl5ka73cLd+5fxIzfNzfgl8NhTbLwngokL7PKcLfgwRpNNhOiM0j44O37BS+Jb7I76aTsgWAmYzh/WDmhvsvP29R0ya3Nu/3nnXaCTc9KkM7xx0yPM9d9Sui2Bi7tONpNk3jmJsa246s+3B+15Bus+BLRcXu3WLmjNYh3B8PylECkC0PxMJ+IKjpd+o8QW+qeOogLtIF6pRCjZJ1m8s04f+WowpxrpjjJgGf8islX4Ob56gImhNJADqE5H/7etkjAJ+0mpwRhb5wcyn7eAfs9f+OYf14TR+iSRdtfWaPUAHs3gUCEylLtSaFkZp1iN6A5KX7cx+AixvNWdrw0rbemWPYjAvGtG9oDVr1WipyWCSp/eaAaMbRzgA/8B1OvjK/GrFOgprjsOb1Pxk3ubBfiILvv5CHzs2b3EHcrfMFB5pW/7n8nnZLrFZrz1fWXGLO2HgodGNkhST1IGej8vuA8mNaCBwMubvbpGuXjf1/XHhTHzJAK5KTM26J9qomOgsigLNT95oXsFsMspJ80MWxLKOltGq41FrRTVSvku5BcvWOdvT5QbaecymHNJKCWYODtfuLhnejNyCDkramC7m69SfDZ4VYGp5Kwxu9RU6lG2K+FahBdYdOJkHXLASAoz8hds=

script:
  - ./scripts/snap.sh $PROJECT
  - ./scripts/push.sh $PROJECT
