name: consul-elopio
version: master
summary: Consul is a tool for service discovery, monitoring and configuration
description: |
  Consul is distributed, highly available, and extremely scalable.
  Consul provides service discovery, health checking, key/value storage and
  multi-datacenter.
confinement: strict

apps:
  consul:
    command: consul-snap
    plugs: [network, network-bind, network-observe, tools]

plugs:
  tools:
    interface: content
    content: healthcheck-toolbox
    target: tools
    default-provider: healthcheck-toolbox-example:toolbox

parts:
  consul:
    source: https://github.com/hashicorp/consul.git
    source-tag: master
    plugin: go
    go-importpath: github.com/hashicorp/consul
  script:
    source: .
    plugin: dump
    snap: ["consul-snap", "tools"]
