name: packer
version: master
summary: Packer - Build Automated Machine Images
description: |
  Packer is easy to use and automates the creation of any type of machine
  image. It embraces modern configuration management by encouraging you to use
  automated scripts to install and configure the software within your
  Packer-made images. Packer brings machine images into the modern age,
  unlocking untapped potential and opening new opportunities.

grade: devel
confinement: strict

apps:
  packer:
    command: packer
    plugs: [home, network]

parts:
  packer:
    source: https://github.com/hashicorp/packer.git
    source-tag: master
    plugin: go
    go-importpath: github.com/hashicorp/packer
    go-packages: [github.com/hashicorp/packer]
    go-buildtags: [core]
    after: [go]
  go:
    source-tag: go1.8
